# this file is the manifest definition for a mod (packed or unpacked)
# each 'mod' needs to have one to tell the game how to deserialize

# the 'id' of the mod is the folder name

# the name for the mod
name = "Core"

textureSizeCaps = [ 0, 128, 256, 512, 1024, 2048, 4096, 8192 ]
supportedShadowMaps = [ 512 , 1024 , 2048 , 4096 , 8192 , 16384 ]
simulationSpeeds = [ 0, 0.1, 1, 2, 4, 10, 30, 120, 600, 1200, 3600, 14400, 86400, 604800, 2592000 ]

# these xml definitions are loaded for planet LODs
planetMeshes = [ "DefaultMeshes.xml", "OptimizedMeshes.xml" ]

# these xml definitions are loaded for celestial system templates
systems = [ "SolSystem.xml", "EarthSystem.xml" , "EarthOnly.xml", "KerbolSystem.xml" ]

# asset xml definitions allow generic pools of assets to be loaded for use through the project, such as meshes and textures
assets = [ "DefaultAssets.xml", "PartAssets.xml", "ExhaustAssets.xml", "Gauges.xml", "Astronomicals.xml" ]

# data to load for star instances
starBinaries = [ "hip_main.bin" ]

# fonts the player can select
fonts = [ "JetBrainsMono-Regular.ttf" ]

[console]
onLoad = [ "simspeed 1", "follow Rocket", "control Rocket", "camera orbit -2.766 -0.12 2.254" ]
